"""field level deleted

Revision ID: 1102f8715228
Revises: 71232bb4e72e
Create Date: 2026-04-23 00:12:35.089657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1102f8715228'
down_revision: Union[str, Sequence[str], None] = '71232bb4e72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productattributelink', 'level')
    op.drop_column('variantattributelink', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variantattributelink', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productattributelink', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
