"""attribute added

Revision ID: 71232bb4e72e
Revises: 
Create Date: 2026-04-22 23:58:42.849994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71232bb4e72e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productattributelink', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('variantattributelink', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variantattributelink', 'level')
    op.drop_column('productattributelink', 'level')
    # ### end Alembic commands ###
