"""enum status in order

Revision ID: bb6884eed0c2
Revises: d0621b435635
Create Date: 2026-04-26 12:50:47.709912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb6884eed0c2'
down_revision: Union[str, Sequence[str], None] = 'd0621b435635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',  
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('created', 'canceled', 'shipped', name='orderstatus'),
               existing_nullable=False, postgresql_using="status::orderstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.Enum('created', 'canceled', 'shipped', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False, postgresql_using="status::varchar")
    # ### end Alembic commands ###
