services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "********"
      POSTGRES_DB: shopDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./data/backup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - app_network
  main:
    build: /app
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_network
  parser:
    build:
      context: .
      dockerfile: parser_app/Dockerfile 
    container_name: parser_app
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8001:8000"
      - "6080:6080"
    networks:
      - app_network
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network
  worker:
    build: ./worker
    command: celery -A celery_config.celery_app worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis
      - parser
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0 
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      PARSER_URL: http://parser:8001
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: